heat_template_version: 2015-10-15

#description: A template to create the networking resources.

parameters:
  project:
    type: string
  app_port:
    type: string
  lb_port:
    type: string
  public_net_name:
    type: string
  private_net_name:
    type: string
  private_net_cidr:
    type: string
  private_net_gateway:
    type: string
  private_net_pool_start:
    type: string
  private_net_pool_end:
    type: string


resources:

################
## Networking ##
################

resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private_net_name }

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: { get_param: private_net_cidr }
      gateway_ip: { get_param: private_net_gateway }
      allocation_pools:
        - start: { get_param: private_net_pool_start }
          end: { get_param: private_net_pool_end }

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net_name }

#  router:
#    type: OS::Neutron::Router
#    properties:
#      network: floating
#      external_gateway_info:
#        network: { get_param: public_net }

#  router_interface:
#    type: OS::Neutron::RouterInterface
#    properties:
#      router_id: { get_resource: router }
#      subnet_id: { get_resource: private_subnet }

  sec_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: { get_param: app_port }
          port_range_max: { get_param: app_port }
        - remote_ip_prefix: 10.0.0.0/8
          protocol: tcp
  	direction: ingress
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 10.0.0.0/8
          protocol: tcp
          direction: egress
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 10.0.0.0/8
          protocol: icmp
          direction: ingress
        - remote_ip_prefix: 10.0.0.0/8
          protocol: icmp
          direction: egress


outputs:
  network_id:
    value: { get_resource: private_net }
    description: GUID of the network created by this template
  network_subnet_id:
    value: { get_resource: private_subnet }
    description: GUID of the subnet created by this template
  network_router_id:
    value: { get_resource: router }
    description: GUID of the router created by this templ
