heat_template_version: 2013-05-23

description: >
  HOT template to create a new neutron network plus a router to the public
  network, and for deploying two servers into the new network. The template also
  assigns floating IP addresses to each server so they are routable from the
  public network.

parameters:
  key_name:
    default: jumphost
    type: string
    description: Name of keypair to assign to servers
#  image: 27b81e8d-f567-4d12-90cc-a801d76faf2a #Image id
  image:
    default: ubuntu
    type: string
    description: Name of image to use for servers
  flavor:
    default: "Standard 1GB"
    type: string
    description: Name of flavor to use for servers
  public_net:
    default: floating
    type: string
    description: ID or name of public network for which floating IP addresses will be allocated
  private_net_name:
    default: net-private-01
    type: string
    description: Name of private network to be created
  private_net_cidr:
    default: 10.0.0.0/24
    type: string
    description: Private network address (CIDR notation)
  private_net_gateway:
    default: 10.0.0.1
    type: string
    description: Private network gateway address
  private_net_pool_start:
    default: 10.0.0.10
    type: string
    description: Start of private network IP address allocation pool
  private_net_pool_end:
    default: 10.0.0.250
    type: string
    description: End of private network IP address allocation pool
  project:
     default: 8fdc053da26b47ef9b679e49fe447830
     type: string
     description: ID of project to create resources in

#  min_appservers: 2
#  max_appservers: 2
#  startup_script: "echo $(hostname)"
#  lb_port: 80
#  lb_app_port: 80

################
## Networking ##
################

resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private_net_name }

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: { get_param: private_net_cidr }
      gateway_ip: { get_param: private_net_gateway }
      allocation_pools:
        - start: { get_param: private_net_pool_start }
          end: { get_param: private_net_pool_end }

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: private_subnet }


################
## Instances ###
################

  server1:
    type: OS::Nova::Server
    properties:
      name: Server1
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: server1_port }

  server1_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net }
      fixed_ips:
        - subnet_id: { get_resource: private_subnet }

  server1_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_resource: server1_port }

  server2:
    type: OS::Nova::Server
    properties:
      name: Server2
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: server2_port }

  server2_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net }
      fixed_ips:
        - subnet_id: { get_resource: private_subnet }

  server2_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_resource: server2_port }


#############
## Outputs ##
#############

outputs:
  server1_private_ip:
    description: IP address of server1 in private network
    value: { get_attr: [ server1, first_address ] }
  server1_public_ip:
    description: Floating IP address of server1 in public network
    value: { get_attr: [ server1_floating_ip, floating_ip_address ] }
  server2_private_ip:
    description: IP address of server2 in private network
    value: { get_attr: [ server2, first_address ] }
  server2_public_ip:
    description: Floating IP address of server2 in public network
    value: { get_attr: [ server2_floating_ip, floating_ip_address ] }
