heat_template_version: 2015-10-15

#description: Create InstanceFloat

parameters:
  name:
    type: string
  key_name:
    type: string
  image:
    type: string
  flavor:
    type: string
  sec_group:
    type: string
  private_net:
    type: string
  private_subnet:
    type: string
  public_net:
    type: string
  reserved_floating_ip:
    type: string
  user_data:
    type: string

resources:

################
## Instances ###
################

  instance:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks: [{ network: { get_param: private_net }}]
      security_groups: [{ get_param: sec_group }]
      user_data_format: RAW
      user_data: { get_param: user_data }

  instance_floating_ip_assoc0_instance0:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_param: reserved_floating_ip }
      server_id: { get_resource: instance }

outputs:
  instance_resource_id:
    description: The id of each deployed instance
    value: { get_resource: instance }
  instance_ip:
    description: "ip address"
    value: { get_attr: [ instance, first_address ]}


